### ISSUE TITLE
Add link to the field guide to the repository metadata

### ISSUE THREAD

**Issue by nuest** [sellorm/field-guide-to-the-r-ecosystem#7]
I suggest to add a [the website link to the field guide](http://fg2re.sellorm.com/) to the repository metadata, i.e. at the top next to the short description.

![image](https://user-images.githubusercontent.com/1325054/34513842-93e9a778-f06a-11e7-9b1d-2fbc37af4832.png)

**Comment by sellorm** [comment]
Done - thanks!
